// Auto generated by utensor-cli

#ifndef __UTENSOR-SIMULATION_MODELS_FREEZED_MODEL_H
#define __UTENSOR-SIMULATION_MODELS_FREEZED_MODEL_H
#include "uTensor/core/context.hpp"
void get_freezed_model_ctx(Context& ctx, Tensor* input_0);
#endif // __UTENSOR-SIMULATION_MODELS_FREEZED_MODEL_H