// Auto generated by utensor-cli

#include "freezed_model.hpp"
#include "uTensor/core/tensor.hpp"
#include "freezed_model_weight.hpp"
#include "uTensor/ops/MathOps.hpp"
#include "uTensor/core/context.hpp"


void get_freezed_model_ctx(Context& ctx, Tensor* input_0) {

{ // add tensor for placeholders
    ctx.add(input_0, "input:0", 1);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_a_0), 
            "a:0", 
            1);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_b_0), 
            "b:0", 
            1);
}
{
    ctx.add(new RamTensor<int>(), "add:0", 1);
    ctx.push(new AddOp<int, int>(),
             { "a:0", "b:0" }, 
             { "add:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "add_1:0");
    ctx.push(new AddOp<int, int>(),
             { "add:0", "input:0" }, 
             { "add_1:0" });
}
}